class PostsController < ApplicationController
  # removed index route for posts bec.the posts index view is no longer needed
  # due to nesting, they appear under topics show view
  #  def index
  #  @posts = Post.all
  # end

  def show
    # find the post that corresponds to the id in the params that were passed to
    # show and assign it to @post.Populate the instance var in a SINGLE post
    @post = Post.find(params[:id])
  end

  def new
  #create an instance var, @post
  #then assign it an empty post returned by Post.new
    @topic = Topic.find(params[:topic_id])   # added to for nesting posts in topic
    @post = Post.new
  end

  def create
   @post = Post.new
   @post.title = params[:post][:title]
   @post.body = params[:post][:body]
   @topic = Topic.find(params[:topic_id])
   @post.topic = @topic

   #if successful save, display success message with flash[:noteice]
   #and redirect user to route generated by @post
   if @post.save
      # assign a value to flash[:notice] The flash has provides
      # a way to pass temp values between actions. Avail in next action
     # then deleted
     flash[:notice] = "Post was saved."
     redirect_to [@post.topic, @post]
   else
   # if not successful in save, display error, render the new view again
     flash.now[:alert] = "There was an error saving the post. Please try again."
     render :new
   end
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.title = params[:post][:title]
    @post.body = params[:post][:body]

    if @post.save
      flash[:notice] = "Post was updated."
      redirect_to [@post.topic, @post]
   else
     flash.now[:alert] = "An error occurred in saving your post. Please try again."
     render :edit
    end
  end

  def destroy
    @post = Post.find(params[:id])

    # call destroy on post, if successful set set a flash message & return to posts index view
    # if destroy fails, set a alert message and return to show view
      if @post.destroy
        flash[:notice] = "\"#{@post.title}\" was deleted successfully."
        redirect_to @post.topic
      else
        flash.now[:alert] = "There was an error in deleting your post."
        render :show
      end
  end
end
